### ISSUE TITLE
[BUG] Error on running app

### ISSUE THREAD

**Issue by hv7214** [HTTP-APIs/hydra-python-agent#132]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:
Followed all steps given in README.md, and then ran `python app.py` resulted in error.

### Expected Behaviour:
App should be up on `localhost:3000`.

### Steps to reproduce:
Follow steps given in README.md

### Log
Traceback (most recent call last):
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ff0371452b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /serverapi/vocab (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff0371452b0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 15, in <module>
    agent = Agent(url)
  File "/home/harshit/hydra-python-agent-gui/venv/src/hydra-agent/hydra_agent/agent.py", line 30, in __init__
    self.fetch_apidoc()
  File "/home/harshit/hydra-python-agent-gui/venv/src/hydra-agent/hydra_agent/agent.py", line 47, in fetch_apidoc
    jsonld_api_doc = super().get(self.entrypoint_url + '/vocab').json()
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /serverapi/vocab (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff0371452b0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by xadahiya** [comment]
Do you have hydrus running?

**Comment by hv7214** [comment]
yeah somehow server got down. Now after turning it up i'm getting this error:
`loading... of graph
creating entrypoint node
split entrypoint into 2 types of endpoints collection and classes
classes endpoint or accessing classes
accessing every collection in entrypoint
commiting
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    agent = Agent(url)
  File "/home/harshit/hydra-python-agent-gui/venv/src/hydra-agent/hydra_agent/agent.py", line 31, in __init__
    self.initialize_graph()
  File "/home/harshit/hydra-python-agent-gui/venv/src/hydra-agent/hydra_agent/agent.py", line 58, in initialize_graph
    self.graph.main(self.entrypoint_url, self.api_doc, True)
  File "/home/harshit/hydra-python-agent-gui/venv/src/hydra-agent/hydra_agent/redis_core/graph_init.py", line 69, in main
    self.redis_graph.commit()
  File "/home/harshit/hydra-python-agent-gui/venv/src/redisgraph/redisgraph/graph.py", line 96, in commit
    return self.query(query)
  File "/home/harshit/hydra-python-agent-gui/venv/src/redisgraph/redisgraph/graph.py", line 130, in query
    response = self.redis_con.execute_command("GRAPH.QUERY", self.name, q, "--compact")
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/redis/client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/redis/client.py", line 853, in parse_response
    response = connection.read_response()
  File "/home/harshit/hydra-python-agent-gui/venv/lib/python3.6/site-packages/redis/connection.py", line 718, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'GRAPH.QUERY'`

**Comment by Mec-iS** [comment]
@Guttz please give a hint

**Comment by Guttz** [comment]
For you to run the client you need:
1 - Running hydrus (the server)
2 - Running Redis Server(local client caching)
3 - Run the Client

Did you run the specified Redis version? `sudo docker run -p 6379:6379 -it --rm redislabs/redisgraph:2.0-edge`

**Comment by Guttz** [comment]
**Other people have been having similar problems.** When you guys are able to solve these issues and manage to run everything, make sure to open a PR to update the readme if you feel you can make it better, please.
