### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'pip._internal.download'

### ISSUE THREAD

**Issue by PrathamDogra** [HTTP-APIs/hydra-python-agent#133]
### I'm submitting a 
- [x] bug report.
- [x] feature request.

### Current Behaviour:
I was trying to run the hydra-python-agent on my computer using Ubuntu terminal while running hydrus on another terminal. I have followed the steps mentioned in README.md. Everything worked fine(including the redis graph) but python3 setup.py install command is giving the following mentioned error.

### Expected Behaviour:
Hydra API client will set up.

### Steps to reproduce:
Follow steps given in README.md

### Error Log
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from pip._internal.download import PipSession
ModuleNotFoundError: No module named 'pip._internal.download'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'

**Comment by Mec-iS** [comment]
please provide Python and Pip versions

**Comment by PrathamDogra** [comment]
My pip version is 20.0.2 and Python version is 3.6.9
I tried to downgrade my pip to 9.0.1 in order to remove the error but the error still prevails.

**Comment by xadahiya** [comment]
@PrathamDogra See this https://stackoverflow.com/questions/25192794/no-module-named-pip-req

This change happened quite recently, you can create a PR to fix this if you want.

**Comment by PrathamDogra** [comment]
Sure @xadahiya  I will create the PR to fix this issue.

**Comment by amalthundiyil** [comment]
I think this issue should be closed since most of the solutions of resolving it as mentioned before involve upgrading or reinstalling pip. Moreover, I am not able to reproduce it locally on my system (Ubuntu 20.04, pip 22.0.3).
